script: "bundle exec rake"

cache:
  bundler: true

rvm:
  - 2.5.8
  - 2.6.6
  - 2.7.1

gemfile:
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_6.0.gemfile

notifications:
  email:
    - brian@spreecommerce.com
    - ryan@spreecommerce.com

matrix:
  exclude:
  - rvm: 2.6.6
    gemfile: gemfiles/rails_5.2.gemfile
  - rvm: 2.7.1
    gemfile: gemfiles/rails_5.2.gemfile
