script: "bundle exec rake"
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
gemfile:
  - gemfiles/rails3_1.gemfile
  - gemfiles/rails3_2.gemfile
  - gemfiles/rails4_0.gemfile
  - gemfiles/haml3_2.gemfile

notifications:
  email:
    - brian@spreecommerce.com
    - ryan@spreecommerce.com

